export const projects = [
    {
        name: '1P Toolkit',
        thumbnail: 'https://s3.amazonaws.com/arbelaez/1P+Toolkit+-+Compressed.png',
        image: 'https://s3.amazonaws.com/arbelaez/1P+Toolkit.png',
        icon1: 'https://s3.amazonaws.com/arbelaez/html48.png',
        icon2: 'https://s3.amazonaws.com/arbelaez/css48.png',
        icon3: 'https://s3.amazonaws.com/arbelaez/react48.png',
        icon4: 'https://s3.amazonaws.com/arbelaez/node48.png',
        icon5: '',
        icon6: '',
        link: 'https://github.com/JosephArbelaez/inyoface-API',
        p1: 'User can insert item IDs and it will return item information.',
        p2: 'User has two options of uploading SKUs.',
        p3: 'User can compare two excels for comprable SKUs.',
    },
    {
        name: 'Inyoface',
        thumbnail: 'https://s3.amazonaws.com/arbelaez/Inyoface+-+Compressed.png',
        image: 'https://s3.amazonaws.com/arbelaez/Inyoface.png',
        icon1: 'https://s3.amazonaws.com/arbelaez/html48.png',
        icon2: 'https://s3.amazonaws.com/arbelaez/css48.png',
        icon3: 'https://s3.amazonaws.com/arbelaez/react48.png',
        icon4: 'https://s3.amazonaws.com/arbelaez/node48.png',
        icon5: '',
        icon6: '',
        link: 'https://github.com/JosephArbelaez/inyoface-API',
        p1: 'User can create a profile & log in',
        p2: 'User can upload an image',
        p3: 'Detected faces display a blue box.',
    },
    {
        name: 'Littr',
        thumbnail: 'https://s3.amazonaws.com/arbelaez/Bulbasaur.jpg',
        image: '',
        icon1: 'https://s3.amazonaws.com/arbelaez/html48.png',
        icon2: 'https://s3.amazonaws.com/arbelaez/css48.png',
        icon3: 'https://s3.amazonaws.com/arbelaez/angular-48.png',
        icon4: '',
        icon5: '',
        icon6: '',
        link: 'https://github.com/JosephArbelaez/1802-banking-JosephArbelaez',
        p1: 'User can create a profile',
        p2: 'User create text or image posts.',
        p3: 'User can manage their profile.',
    },
    {
        name: 'Banking App',
        thumbnail: 'https://s3.amazonaws.com/arbelaez/Bulbasaur.jpg',
        image: '',
        icon1: 'https://s3.amazonaws.com/arbelaez/html48.png',
        icon2: 'https://s3.amazonaws.com/arbelaez/css48.png',
        icon3: 'https://s3.amazonaws.com/arbelaez/js48.png',
        icon4: '',
        icon5: '',
        icon6: '',
        link: 'https://github.com/JosephArbelaez/1802-banking-JosephArbelaez',
        p1: 'User can login and logout.',
        p2: 'User has a balance.',
        p3: 'User can withdraw and deposit.',
    },
];